### ISSUE TITLE
Ability to 'see' headers defined in RAML

### ISSUE THREAD

**Issue by scordatura** [cybertk/abao#24] opened 2014-12-26 22:46 UTC
We can specify headers in RAML, for example:

```
resourceTypes:
  - collection-item:
      description: | 
        GET shows an individual <<resourcePathName|!singularize>>
      get:
        description: Get a list of <<resourcePathName>>.
        headers: &commonHeaders
          accept: 
            displayName: Accept
            description: MIME types that client is willing to accept.
            example: "*/*"
          content-type: 
            displayName: Content Type
            description: MIME type of document being served.
            example: "application/x-www-form-urlencoded,application/json"
```
...then later on:

```
/lakes/{id}:
    description: |  
      A collection of descriptions of the deepest lakes in the world.
    uriParameters:
      id:
        description: |
          A two-digit integer that serves as the ID of a lake. For example, 01 is the ID for Lake Baikal.
        type: integer
        example: 01
    type:
      collection-item:
        exampleItem: !include lakes-item.sample
    get:
      headers: *commonHeaders
```

Version 0.2.5 of Abao does not 'see' these headers. We are forced to specify the headers at the command line:

```
abao api.raml https://lakes-api.example.com -h 'Accept:*/*' -h 'Content-Type:application/x-www-form-urlencoded,application/json' --hookfiles=hook.coffee

```

**Note:** There is more than one way to specify headers in RAML. The syntax shown above is just one way.

Please improve Abao by adding the ability to 'see' the headers specified in the RAML, so that we can stop specifying headers at the command line. Thanks!

**Comment by cybertk** [comment] 2015-01-27 07:34
@scordatura I cannot reproduce this issue, is your problem still exist?

**Comment by scordatura** [comment] 2015-01-27 20:38
Hi @cybertk, thanks for checking ... yes, the problem still exists. 

When the abao command includes headers, all tests pass. 

When the abao command does not include headers, the 500 tests fail because the API returns 200 and a bunch of HTML.

**Comment by cybertk** [comment] 2015-01-28 03:24
@scordatura Could you mind share your env? So that I can find the root cause.

**Comment by scordatura** [comment] 2015-01-28 22:34
Hi @cybertk, 
I am attaching all the files for a test API. This is not a working example because my work is not public yet, so I changed names of resources. But you can see what I'm doing. Please let me know if you have questions.

```
#%RAML 0.8
baseUri: https://labs.rocketfuel.com
title: Testable
version: 0.1

schemas:
 - widget: !include widget.schema
 - widgets: !include widget-list.schema

resourceTypes:
  - collection:
      description: | 
        The <<resourcePathName>> collection.
      get:
        description: Get a list of <<resourcePathName>>.
        headers: &commonHeaders
          accept: 
            displayName: Accept
            description: MIME types that client is willing to accept.
            example: "application/json, text/javascript, */*"
          content-type: 
            displayName: Content Type
            description: MIME type of document being served.
            example: "application/x-www-form-urlencoded,application/json"
        responses:
          200:
            body:
              application/json:
                example: |
                  <<exampleCollection>>
                schema: <<schema>>
          500:
            body:
              application/json:
                example: |
                  {"message": "Internal server error" }
  - collection-item:
      description: | 
        A member of the <<resourcePathName>> collection.
      get:
        description: |
         GET shows an individual <<resourcePathName|!singularize>>
        headers: *commonHeaders
        responses:
          200:
            body:
              application/json:
                example: |
                  <<exampleItem>>
                schema: <<schema>>
          404:
            body:
              application/json:
                example: |
                  {"message": "Record not found: Couldn't find requested <<resourcePathName|!singularize>>" }
          500:
            body:
              application/json:
                example: |
                  {"message": "Internal server error" }
/widgets:
  type: 
    collection: 
      exampleCollection: !include widgets-get-collection.sample
      schema: widgets
  /{id}:
    description: |
      TBD.
    uriParameters:
      id:
        description: |
          TBD.
        type: integer
        example: 718
    type:
      collection-item: 
        exampleItem: !include widgets-get-item.sample
        schema: widget
```

**Comment by scordatura** [comment] 2015-01-28 22:34
```
[
    {
        "elasticity": 3,
        "id": 782,
        "is_acute": true,
        "name": "A Bientot"
    },

    {
        "elasticity": 1,
        "id": 718,
        "is_acute": true,
        "name": "Da Svidanye"
    },
    {
        "elasticity": 1,
        "id": 790,
        "is_acute": true,
        "name": "Ta ta for now"
    },
    {
        "elasticity": 4,
        "id": 707,
        "is_acute": true,
        "name": "Hasta la proxima"
    }
]
```

**Comment by scordatura** [comment] 2015-01-28 22:36
*widgets-get-item.sample*

```
{
    "elasticity": 2,
    "id": 777,
    "is_acute": true,
    "name": "Get thee hence"
}
```

**Comment by scordatura** [comment] 2015-01-28 22:37
*widget-schema*

```
{
  "$schema":"http://json-schema.org/draft-04/schema#",
  "title":"",
  "description":"",
  "required": ["elasticity","id","is_acute","name"],
  "properties": { 
    "elasticity": {"type":"integer"},
    "id": {"type":"integer"},
    "is_acute": {"type":"boolean"},
    "name": {"type":"string"}
  }
}
```

**Comment by scordatura** [comment] 2015-01-28 22:38
*widget-list.schema*

```
{
  "$schema":"http://json-schema.org/draft-04/schema#",
  "title":"",
  "description":"",
  "type":"array",
      "items":
      {
        "type":"object",
        "additionalProperties":false,
        "required": ["elasticity","id","is_acute","name"],
        "properties": { 
          "elasticity": {"type":"integer"},
          "id": {"type":"integer"},
          "is_acute": {"type":"boolean"},
          "name": {"type":"string"}
        }
      }
}
```

**Comment by cybertk** [comment] 2015-01-29 08:17
@scordatura I tried to simulate your env with the RAML/hooks you provided above. It has been committed to **bug/24** branch. I still cannot reproduce your issue.

You can reproduce the issue via
```
git checkout bug/24
grunt coffee
cd bug-24
../bin/abao bug.raml http://localhost:3333 --hookfiles=widget-hook.coffee
```

The result in my env is 
```
$ ../bin/abao bug.raml http://localhost:3333 --hookfiles=widget-hook.coffee Found Hookfiles: widget-hook.coffee


  GET /widgets -> 200
    ✓ Validate response code and body

  GET /widgets -> 500
    ✓ Validate response code only

  GET /widgets/{id} -> 200
    ✓ Validate response code and body

  GET /widgets/{id} -> 404
    ✓ Validate response code only

  GET /widgets/{id} -> 500
    ✓ Validate response code only


  5 passing (60ms)
```

**Comment by scordatura** [comment] 2015-01-30 01:14
Thanks, @cybertk, i have followed your instructions, and you are correct, abao works fine with the "widgets" API, and there is no need for the -h option.

So the problem must be in my environment somehow. a developer here is helping me and we will let you know what we find.

**Comment by scordatura** [comment] 2015-02-10 02:39
@cybertk, your test environment listens on localhost port 3333. 

Is there a log to show exactly what requests come into that port? Thanks!

**Comment by cybertk** [comment] 2015-02-10 05:24
You can print logs in `bug-24/bug-server.js`

**Comment by cybertk** [comment] 2015-03-10 00:18
Is there any update on this topic?

**Comment by scordatura** [comment] 2015-03-10 00:41
Not yet, unfortunately. Maybe later this week.

Abraham Raher | *Apps Team Technical Writer*

**Comment by scordatura** [comment] 2015-04-16 19:24
This problem persisted until we changed the value of the Accept header to **/** in the RAML. 

With that change, everything works.

**Closed** 2015-04-16 19:25 UTC
Labels: feature
