### ISSUE TITLE
Can't get xunit nor tap output reporters to work

### ISSUE THREAD

**Issue by abienkowski** [cybertk/abao#59] opened 2015-12-17 20:40 UTC
abao <raml file> <host> -R xunit  produces same output to stdout as spec reporter, this is the same for tap reporter.

**Comment by maremmle** [comment] 2016-02-03 19:57
it's `-r` (lowercase)

**Comment by plroebuck** [comment] 2016-02-29 00:22
Closing as user error. Cannot reproduce.

**Closed by plroebuck** 2016-02-29 00:22 UTC
Labels: bug
